### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by yannpub** [saniho/apiNetatmo#11]
I cannot identify the date and/or the triggering event, but I have the following error now in the integration:

2023-12-15 09:21:36.832 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up apiNetatmo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/apiNetatmo/sensor.py", line 95, in setup_platform
    myNet.update()
  File "/config/custom_components/apiNetatmo/sensor.py", line 66, in update
    token = self._myNetatmo.authenticate()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/apiNetatmo/apiNetatmo.py", line 149, in authenticate
    self.accessToken()
  File "/config/custom_components/apiNetatmo/apiNetatmo.py", line 124, in accessToken
    if self.expiration < time.time() : self.renew_token()
                                       ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/apiNetatmo/apiNetatmo.py", line 116, in renew_token
    if self.refreshToken != resp['refresh_token']:
                            ~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by yannpub** [comment]
Fixed with release 1.1.1.0

Thanks !!
