### ISSUE TITLE
apiNetatmo Sensor doesn't work anymore since something changed at Netatmo logic

### ISSUE THREAD

**Issue by cwm77** [saniho/apiNetatmo#14]
First, thank you for the excellent implementation. I really like and need it for wind forecasts in the area I live. I use the data for controlling my pergola to wrap it in time before the wind is reaching my garden.

Unfortunately, I am not a developer and therefore cannot determine the reason why the sensor has not been working since last weekend. However, I assume that it has to do with another change on the part of netatmo. I would be delighted if someone could find the cause. I can help with information. the HA log says: 

`Error while setting up apiNetatmo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/apiNetatmo/sensor.py", line 97, in setup_platform
    myNet.update()
  File "/config/custom_components/apiNetatmo/sensor.py", line 67, in update
    token = self._myNetatmo.authenticate()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/apiNetatmo/apiNetatmo.py", line 151, in authenticate
    self.accessToken()
  File "/config/custom_components/apiNetatmo/apiNetatmo.py", line 126, in accessToken
    if self.expiration < time.time() : self.renew_token()
                                       ^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/apiNetatmo/apiNetatmo.py", line 118, in renew_token
    if self.refreshToken != resp['refresh_token']:
                            ~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable`

**Comment by yannpub** [comment]
Go to your netatmo dev portal, refresh the tokens, update your config yaml accordingly, and it should be fine.
**Edit:** It works only once. Values are retrieved once, but not more. Then we get back to the error message :-(
