### ISSUE TITLE
Integration 1.1.0 does not refresh after initial start

### ISSUE THREAD

**Issue by yannpub** [saniho/apiNetatmo#8]
The integration gets proper values from the netatmo site when HA is started, however it doesn't get further updates after the initial start. The errors below start after the duration of the first scan_interval (600s).

This error originated from a custom integration.

Logger: homeassistant.helpers.entity
Source: custom_components/apiNetatmo/apiNetatmo.py:187
Integration: apiNetatmo (documentation)
First occurred: 2:17:18 PM (65 occurrences)
Last logged: 2:57:25 PM

Update for sensor.mynetatmo_70_ee_50_2a_f5_f2_montauroux_dernieresynchro fails
Update for sensor.mynetatmo_70_ee_50_3e_e2_5c_montauroux_temperature fails
Update for sensor.mynetatmo_70_ee_50_3e_e2_5c_montauroux_humidity fails
Update for sensor.mynetatmo_70_ee_50_3e_e2_5c_montauroux_pressure fails
Update for sensor.mynetatmo_70_ee_50_3e_e2_5c_montauroux_dernieresynchro fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 695, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/apiNetatmo/sensor.py", line 158, in _update
    self._myNet.update()
  File "/config/custom_components/apiNetatmo/sensor.py", line 70, in update
    self._lstStation = self._myNetatmo.update_favorites_stations( self._lstStation )
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/apiNetatmo/apiNetatmo.py", line 187, in update_favorites_stations
    for device in data['devices']:
                  ~~~~^^^^^^^^^^^
KeyError: 'devices'

**Comment by saniho** [comment]
ty, correct in the last pre release 1.1.0.1
